# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f576a87176c1174f2985918166b85c07e2a1f91d2ef8c9c38b376f560aeea53068558899877c6106d00dff72d34cc2aab1def31faa97c6c0c56816996cace480

test:
  secret_key_base: ceec258341ac41fd4a18a7fd59c5e1ee0a65bc974b0bd2a83b85e1bc34cc368d26fbee119875d38935640b59d4dbe655bdb7f063172e185f7ca1c94a106f9218

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
